### ISSUE TITLE
transforms.py exception

### ISSUE THREAD

**Issue by fatly** [HRNet/HRNet-Facial-Landmark-Detection#56]
Epoch: [0][0/469]       Time 9.469s (9.469s)    Speed 1.7 samples/s     Data 5.064s (5.064s)    Loss 0.00306 (0.00306)
Epoch: [0][50/469]      Time 1.203s (1.376s)    Speed 13.3 samples/s    Data 0.000s (0.100s)    Loss 0.00166 (0.00177)
Epoch: [0][100/469]     Time 1.218s (1.291s)    Speed 13.1 samples/s    Data 0.000s (0.051s)    Loss 0.00160 (0.00170)
Epoch: [0][150/469]     Time 1.203s (1.266s)    Speed 13.3 samples/s    Data 0.000s (0.034s)    Loss 0.00155 (0.00166)
Epoch: [0][200/469]     Time 1.187s (1.250s)    Speed 13.5 samples/s    Data 0.000s (0.026s)    Loss 0.00135 (0.00161)
Epoch: [0][250/469]     Time 1.203s (1.243s)    Speed 13.3 samples/s    Data 0.000s (0.021s)    Loss 0.00122 (0.00155)
Epoch: [0][300/469]     Time 1.203s (1.237s)    Speed 13.3 samples/s    Data 0.000s (0.017s)    Loss 0.00120 (0.00150)
Epoch: [0][350/469]     Time 1.234s (1.233s)    Speed 13.0 samples/s    Data 0.000s (0.015s)    Loss 0.00115 (0.00146)
Traceback (most recent call last):
  File "tools/train.py", line 144, in <module>
    main()
  File "tools/train.py", line 116, in main
    function.train(config, train_loader, model, criterion,
  File "tools\..\lib\core\function.py", line 57, in train
    for i, (inp, target, meta) in enumerate(train_loader):
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Projects\Github\HRNet-Facial-Landmark-Detection\tools\..\lib\datasets\wflw.py", line 75, in __getitem__
    img = crop(img, center, scale, self.input_size, rot=r)
  File "E:\Projects\Github\HRNet-Facial-Landmark-Detection\tools\..\lib\utils\transforms.py", line 207, in crop
    new_img[new_y[0]:new_y[1], new_x[0]:new_x[1]] = img[old_y[0]:old_y[1], old_x[0]:old_x[1]]
ValueError: could not broadcast input array from shape (203,0,3) into shape (203,194,3)

**Comment by mucunwuxian** [comment]
@fatly 
Hi!✋
In my case, I confirmed the same error when the calculation result of annotation center_w, center_h was incorrect.
After that, when I recalculated correctly, the error disappeared.
FYI!

**Comment by liuleiBUAA** [comment]
> @fatly
> Hi!✋
> In my case, I confirmed the same error when the calculation result of annotation center_w, center_h was incorrect.
> After that, when I recalculated correctly, the error disappeared.
> FYI!

hi, I have the same error, where should I fix the code, thank you

**Comment by Nancy-Wen** [comment]
@mucunwuxian I have the same error with wflw and 300w datasets in training and testing, can you tell me how to calculation the correct  annotation center_w and center_h? Thank you very much!

**Comment by mucunwuxian** [comment]
@fatly @Nancy-Wen 
Sorry for my late reply. 🙇
Actually, it was before, so I've forgotten a lot ...

For example, in the case of 300w, I think it was necessary to prepare csv datas from the .pts file, like the layout below.

```
image_name,scale,center_w,center_h,original_0_x,original_0_y,original_1_x,original_1_y,original_2_x,original_2_y,original_3_x,original_3_y,original_4_x,original_4_y,original_5_x,original_5_y,original_6_x,original_6_y,original_7_x,original_7_y,original_8_x,original_8_y,original_9_x,original_9_y,original_10_x,original_10_y,original_11_x,original_11_y,original_12_x,original_12_y,original_13_x,original_13_y,original_14_x,original_14_y,original_15_x,original_15_y,original_16_x,original_16_y,original_17_x,original_17_y,original_18_x,original_18_y,original_19_x,original_19_y,original_20_x,original_20_y,original_21_x,original_21_y,original_22_x,original_22_y,original_23_x,original_23_y,original_24_x,original_24_y,original_25_x,original_25_y,original_26_x,original_26_y,original_27_x,original_27_y,original_28_x,original_28_y,original_29_x,original_29_y,original_30_x,original_30_y,original_31_x,original_31_y,original_32_x,original_32_y,original_33_x,original_33_y,original_34_x,original_34_y,original_35_x,original_35_y,original_36_x,original_36_y,original_37_x,original_37_y,original_38_x,original_38_y,original_39_x,original_39_y,original_40_x,original_40_y,original_41_x,original_41_y,original_42_x,original_42_y,original_43_x,original_43_y,original_44_x,original_44_y,original_45_x,original_45_y,original_46_x,original_46_y,original_47_x,original_47_y,original_48_x,original_48_y,original_49_x,original_49_y,original_50_x,original_50_y,original_51_x,original_51_y,original_52_x,original_52_y,original_53_x,original_53_y,original_54_x,original_54_y,original_55_x,original_55_y,original_56_x,original_56_y,original_57_x,original_57_y,original_58_x,original_58_y,original_59_x,original_59_y,original_60_x,original_60_y,original_61_x,original_61_y,original_62_x,original_62_y,original_63_x,original_63_y,original_64_x,original_64_y,original_65_x,original_65_y,original_66_x,original_66_y,original_67_x,original_67_y
01_Indoor/indoor_001.png,1.00651,546.6510000000001,181.2175,446.0,91.0,449.459,119.344,450.957,150.614,460.552,176.986,471.486,202.157,488.087,226.842,506.016,246.438,524.662,263.865,553.315,271.435,578.732,266.26,599.361,248.966,615.947,220.651,627.439,197.999,635.375,179.064,642.063,156.371,647.302,124.753,646.518,92.944,470.271,117.87,486.218,109.415,503.097,114.454,519.714,120.09,533.68,127.609,571.937,123.59,585.702,117.155,602.344,109.07,620.077,103.951,633.964,111.236,554.931,145.072,554.589,161.106,554.658,177.57,554.777,194.295,532.717,197.93,543.637,202.841,555.652,205.483,565.441,202.069,576.368,197.061,487.474,136.436,499.184,132.337,513.781,133.589,527.594,143.047,513.422,144.769,499.117,144.737,579.876,140.815,590.901,130.008,605.648,128.376,618.343,132.671,606.771,140.525,593.466,141.419,519.04,229.04,536.292,221.978,547.001,221.192,557.161,224.381,568.172,219.826,579.144,222.233,589.098,224.41,581.071,239.804,570.103,251.962,558.241,254.844,547.661,254.621,534.085,247.772,524.758,230.477,547.684,231.663,557.304,230.805,568.172,229.159,585.417,225.992,569.211,237.777,557.473,240.542,547.989,240.014
```

The calculation method is https://github.com/HRNet/HRNet-Facial-Landmark-Detection/issues/3.

**Comment by MengHao666** [comment]
> or with wflw and 300w datasets in training and testing, can you tell me how to calculation the correct annotation center_w and center_h? Thank you very much!

Have you sloved the problem?

**Comment by MengHao666** [comment]
> Have you sloved the problem?

Have you sloved the problem?

**Comment by MengHao666** [comment]
Have you sloved the problem?
